### ISSUE TITLE
wrong type for mysql bigint column

### ISSUE THREAD

**Issue by czyt** [ariga/entimport#11]
I create a table with a `bigint`  column,but when generated  scheme using entimport  struct field is `int` ,should it be `int64`  not `int`?

**Comment by zeevmoney** [comment]
> I create a table with a `bigint` column,but when generated scheme using entimport struct field is `int` ,should it be `int64` not `int`?

Hi @czyt,
Please see the Go spec here: https://go.dev/ref/spec#Numeric_types
Using  Go's `Int` for `bigint` columns is valid.

**Comment by Gowa2017** [comment]
> > I create a table with a `bigint` column,but when generated scheme using entimport struct field is `int` ,should it be `int64` not `int`?
> 
> Hi @czyt, Please see the Go spec here: https://go.dev/ref/spec#Numeric_types Using Go's `Int` for `bigint` columns is valid.

Why? The linke says the `int` is impl spec size in 32 or 64 bit. When in amd64 or other 64bit os, it's OK.
But how about I run go program in 32bit machine, and connect to mysql which use bigint type?

https://github.com/ariga/entimport/blob/3381ae96c4900ffab213ab6c5019801d1bc2b9e6/internal/entimport/mysql.go#L125
