### ISSUE TITLE
Blog post this feature

### ISSUE THREAD

**Issue by gedw99** [ariga/entimport#18]
Did this get a blog post  in the Ent web site ?

the reason I raise this is because 
when I discuss ent with long time devs they hate that ent is not database first in terms of the source of the schema.

**Comment by rotemtam** [comment]
hey @gedw99 !
sure, @zeevmoney blogged about this back in last October:
https://entgo.io/blog/2021/10/11/generating-ent-schemas-from-existing-sql-databases
