### ISSUE TITLE
not enough arguments in call to field.JSON

### ISSUE THREAD

**Issue by euskadi31** [ariga/entimport#22]
<img width="499" alt="Capture d’écran 2022-03-01 à 00 29 10" src="https://user-images.githubusercontent.com/195383/156076407-6e3004dd-9e48-4dfe-a669-50cb4963020d.png">

**Comment by zeevmoney** [comment]
Hi @euskadi31,

There is no support yet for JSON fields, see this issue - https://github.com/ariga/entimport/issues/5
