### ISSUE TITLE
Broken method name for MySQL DECIMAL fields

### ISSUE THREAD

**Issue by scathers** [ariga/entimport#25]
When I generate the fields for a MySQL table with `DECIMAL` columns (`DECIMAL(19, 6)` in this case), I'm getting fields like this:
```go
field.Float64("cost")
```
However, this leads to a compilation error, because the method name is actually `Float`, not `Float64`. Right now I have to change it by hand to:
```go
field.Float("cost")
```

**Comment by zeevmoney** [comment]
Hi @scathers, 

I did a the following PR to https://github.com/ent/contrib/pull/278/files to `schemast` (which handles the creation ent schema), once it's merged I will upgrade the dependency and this issue will be resolved.

**Comment by zeevmoney** [comment]
> I did a [PR](https://github.com/ent/contrib/pull/278/files) to `schemast` (which handles the creation ent schema), once it's merged I will upgrade the dependency and this issue will be resolved.

The `schemast` PR was merged, this one fixes your issue: https://github.com/ariga/entimport/pull/26

**Comment by scathers** [comment]
Thanks!

**Comment by zeevmoney** [comment]
@scathers, the PR was merged :) I'm closing this issue. 
Thank you for the feedback!
