### ISSUE TITLE
join tables must be inspected with ref tables - append  `tables` flag

### ISSUE THREAD

**Issue by Faroukhamadi** [ariga/entimport#32]
So I tried generating my ent schema using entimport and everything seemed to work just fine until I noticed that my Join table wasn't in the folder.
I ran this command trying to generate the table:
```
go run ariga.io/entimport/cmd/entimport -tables friendship  -dsn "<mydsn>"
```
but I still got an error telling me that schema import failed:
```
entimport: schema import failed - entimport: join tables must be inspected with ref tables - append 
`tables` flag
```

I've tried the append flag but I can't seem to find it in docs

**Comment by zeevmoney** [comment]
Hi @Faroukhamadi ,

Did you try inspecting all 3 tables with the `tables` flag?

**Comment by Faroukhamadi** [comment]
Hello @zeevmoney , well If I run this command it still generates 3 tables when I have a fourth join table...
```
go run ariga.io/entimport/cmd/entimport -tables header,message,user,friendship   -dsn "postgresql://<username>:<password>@localhost:5432/Connectify?sslmode=disable"
```
This is what my schema looks like
![image](https://user-images.githubusercontent.com/36114668/171283127-c87e313c-de09-473d-aa2b-ad56710464be.png)
