### ISSUE TITLE
entimport should include newlines in generated output

### ISSUE THREAD

**Issue by tmc** [ariga/entimport#34]
entimport should include newlines in generated output

**Comment by rotemtam** [comment]
Its actually a missing feature in https://pkg.go.dev/entgo.io/contrib/schemast

But sure, definitely needed

**Comment by zeevmoney** [comment]
Hi @tmc,

I've added it to the roadmap recently, I'll reference your issue in there

https://github.com/ariga/entimport/issues/27

**Comment by tmc** [comment]
> Its actually a missing feature in https://pkg.go.dev/entgo.io/contrib/schemast
> 
> But sure, definitely needed

@rotemtam can you highlight where in `contrib/schemast` this would be added? I presume a PrintOption?
