### ISSUE TITLE
ent cant generate from incorrect edge (mismatch field types)

### ISSUE THREAD

**Issue by kitchendcardiff** [ariga/entimport#38]
ent generates an error trying to parse the generated schema from the ddl below. The provided error is:
"mismatch field type between edge field "username" and id of type "User" (string != int32)"

```
CREATE TABLE `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(50) NOT NULL,
  `token` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`),
  UNIQUE KEY `token` (`token`)
) ENGINE=InnoDB AUTO_INCREMENT=23 DEFAULT CHARSET=utf8;

CREATE TABLE `programme_uploads` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(50) NOT NULL,
  `upload_time` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `username` (`username`),
  KEY `upload_time_index` (`upload_time`),
  CONSTRAINT `programme_uploads_ibfk_1` FOREIGN KEY (`username`) REFERENCES `users` (`username`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=23 DEFAULT CHARSET=utf8;
```

I think it might be missing the foreign key reference in the generation?

**Comment by giautm** [comment]
Hey @kitchendcardiff, thank you for your time on the issue.

[ent](https://github.com/ent/ent) currently doesn't support FK with the destination isn't a PK.

Can you migrate your database to create the column `programme_uploads.user_id` that reference to `users.id`?

**Comment by kitchendcardiff** [comment]
Unfortunately Its a legacy db I can't change the structure on, but I appreciate the reply and confirmation.
