### ISSUE TITLE
O2M Same Type 

### ISSUE THREAD

**Issue by AristeH** [ariga/entimport#7]
https://github.com/ent/ent/tree/master/examples/o2mrecur
1. Created a NODE table in MySQL.
`// Fields of the Node.
func (Node) Fields() []ent.Field {
	return []ent.Field{
		field.Int("value"),
	}
}

// Edges of the Node.
func (Node) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("children", Node.Type).
			From("parent").
			Unique(),
	}
}`

2. Generating Ent Schemas 
go run ariga.io/entimport/cmd/entimport -dialect mysql -dsn 

`func (Node) Fields() []ent.Field {
	return []ent.Field{field.Int("id"), field.Int("value"), field.

		// Edges of the Node.
		Int("node_children").Optional()}

}

func (Node) Edges() []ent.Edge {
	return []ent.Edge{edge.To("child_nodes", Node.Type), edge.From("parent_node", Node.Type).Unique().Field("node_children")}

}`

3. 
go generate ./ent

entc/gen: missing reference name for inverse edge: Node.parent_node

**Comment by zeevmoney** [comment]
Hi @AristeH,

Thanks for reaching out, and sorry for the late reply.
I ran the example you are referring to with MySQL 8, and got the same result.

This PR fixes it: https://github.com/ariga/entimport/pull/16

After the fix:

```mysql
create table nodes
(
    id            bigint auto_increment
        primary key,
    value         bigint not null,
    node_children bigint null,
    constraint nodes_nodes_children
        foreign key (node_children) references nodes (id)
            on delete set null
)
    collate = utf8mb4_bin;
```

Will result in:


```golang
// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
)

type Node struct {
	ent.Schema
}

func (Node) Fields() []ent.Field {
	return []ent.Field{field.Int("id"), field.Int("value"), field.Int("node_children").Optional()}
}
func (Node) Edges() []ent.Edge {
	return []ent.Edge{edge.To("child_nodes", Node.Type), edge.From("parent_node", Node.Type).Ref("child_nodes").Unique().Field("node_children")}
}
func (Node) Annotations() []schema.Annotation {
	return nil
}
```

And this will generate a correct ent schema.
