### ISSUE TITLE
is it possible to add db pool option

### ISSUE THREAD

**Issue by czyt** [ariga/entimport#9]
see documents on ent site [sql.DB Integration](https://entgo.io/docs/sql-integration/)
we can set db options in the `DB()`  in normal code.but in the generated code, we could not access the DB object.
so if it is possible to add some functional option  to set  `SetMaxIdleConns` `SetMaxOpenConns` `SetConnMaxLifetime`

**Comment by zeevmoney** [comment]
Hi @czyt,

Thanks for reaching out, The purpose of entimort is to take SQL DDL and turn it into `ent` schema definition code. So your issue is relevant for `ent` itself, and should be opened there.
